name: Script no Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  executar-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: npm

      - run: npm ci

      - run: bash scripts/meu-script.sh
